# Generated by Django 4.2.5 on 2023-09-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_date_post_created_post_publish_post_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='pos',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок записи'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
